[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.51"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture"

[context.deploy-preview.environment]
HUGO_VERSION = "0.51"
